apiVersion: v1
kind: Service

metadata:
  name: python-devops-demo

spec:
  type: NodePort

  selector:
    app: python-devops-demo

  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP